# Generated by Django 3.2.5 on 2021-07-25 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_frureview'),
        ('vegetable', '0002_vegreview'),
        ('custamor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModelvegitable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=1)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('costamor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetable.vegitable')),
            ],
        ),
        migrations.CreateModel(
            name='CartModelFruite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=1)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('costamor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.fruits')),
            ],
        ),
    ]
