# Generated by Django 3.2.5 on 2021-08-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='phone_no1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='phone_no2',
            field=models.IntegerField(null=True),
        ),
    ]
