# Generated by Django 3.2.5 on 2021-08-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210809_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='phone_no1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='phone_no2',
            field=models.BigIntegerField(null=True),
        ),
    ]
