# Generated by Django 3.2.5 on 2021-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quanty', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='froot')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='froot')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='froot')),
                ('droup', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('offer', models.BooleanField(default=False)),
                ('des', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
