# Generated by Django 3.2.5 on 2021-07-25 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frureview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costamor_nam', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.TextField(max_length=400)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit.fruits')),
            ],
        ),
    ]
