# Generated by Django 3.2.5 on 2021-08-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_auto_20210803_1246'),
        ('fruit', '0003_alter_fruits_date'),
    ]

    operations = [
    ]
