# Generated by Django 3.2.5 on 2021-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0004_merge_0002_auto_20210803_1246_0003_alter_fruits_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='discount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='tax',
            field=models.FloatField(blank=True, default=0, help_text='Enter the persatage of tax '),
        ),
    ]
