# Generated by Django 3.2.5 on 2021-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegitable',
            old_name='droup',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='vegitable',
            name='pakking',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='vegitable',
            name='tax',
            field=models.FloatField(blank=True, default=0, help_text='Enter the persatage of tax'),
        ),
        migrations.AlterField(
            model_name='vegitable',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
