# Generated by Django 3.2.5 on 2021-07-29 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0002_vegreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegitable',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
